export const NEWS_LIST_QUERY = 'NEWS_LIST_QUERY';
export const NEWS_LIST_SUCCESS = 'NEWS_LIST_SUCCESS';
export const NEWS_LIST_FAIL = 'NEWS_LIST_FAIL';

export const NEWS_SELECT_QUERY = 'NEWS_SELECT_QUERY';
export const NEWS_SELECT_SUCCESS = 'NEWS_SELECT_SUCCESS';
export const NEWS_SELECT_FAIL = 'NEWS_SELECT_FAIL';