export const NEWS_LIST_QUERY = 'NEWS_LIST_QUERY';
export const NEWS_LIST_SUCCESS = 'NEWS_LIST_SUCCESS';
export const NEWS_LIST_FAIL = 'NEWS_LIST_FAIL';
export const NEWS_LIST_RESET = 'NEWS_LIST_RESET';

export const NEWS_SELECT_QUERY = 'NEWS_SELECT_QUERY';
export const NEWS_SELECT_SUCCESS = 'NEWS_SELECT_SUCCESS';
export const NEWS_SELECT_FAIL = 'NEWS_SELECT_FAIL';
export const NEWS_SELECT_RESET = 'NEWS_SELECT_RESET';

export const NEWS_TRANSLATE_QUERY = 'NEWS_TRANSLATE_QUERY';
export const NEWS_TRANSLATE_SUCCESS = 'NEWS_TRANSLATE_SUCCESS';
export const NEWS_TRANSLATE_FAIL = 'NEWS_TRANSLATE_FAIL';
export const NEWS_TRANSLATE_RESET = 'NEWS_TRANSLATE_RESET';