export const NOTE_LIST_QUERY = 'NOTE_LIST_QUERY';
export const NOTE_LIST_SUCCESS = 'NOTE_LIST_SUCCESS';
export const NOTE_LIST_FAIL = 'NOTE_LIST_FAIL';

export const NOTE_QUERY = 'NOTE_QUERY';
export const NOTE_SUCCESS = 'NOTE_SUCCESS';
export const NOTE_FAIL = 'NOTE_FAIL';

export const NOTE_CREATE_QUERY = 'NOTE_CREATE_QUERY';
export const NOTE_CREATE_SUCCESS = 'NOTE_CREATE_SUCCESS';
export const NOTE_CREATE_FAIL = 'NOTE_CREATE_FAIL';

export const NOTE_UPDATE_QUERY = 'NOTE_UPDATE_QUERY';
export const NOTE_UPDATE_SUCCESS = 'NOTE_UPDATE_SUCCESS';
export const NOTE_UPDATE_FAIL = 'NOTE_UPDATE_FAIL';

export const NOTE_DELETE_QUERY = 'NOTE_DELETE_QUERY';
export const NOTE_DELETE_SUCCESS = 'NOTE_DELETE_SUCCESS';
export const NOTE_DELETE_FAIL = 'NOTE_DELETE_FAIL';