export const NOTE_LIST_QUERY = 'NOTE_LIST_QUERY';
export const NOTE_LIST_SUCCESS = 'NOTE_LIST_SUCCESS';
export const NOTE_LIST_FAIL = 'NOTE_LIST_FAIL';

export const NOTE_SELECT_QUERY = 'NOTE_SELECT_QUERY';
export const NOTE_SELECT_SUCCESS = 'NOTE_SELECT_SUCCESS';
export const NOTE_SELECT_FAIL = 'NOTE_SELECT_FAIL';
export const NOTE_SELECT_RESET = 'NOTE_SELECT_RESET';

export const NOTE_CREATE_QUERY = 'NOTE_CREATE_QUERY';
export const NOTE_CREATE_SUCCESS = 'NOTE_CREATE_SUCCESS';
export const NOTE_CREATE_FAIL = 'NOTE_CREATE_FAIL';
export const NOTE_CREATE_RESET = 'NOTE_CREATE_RESET';

export const NOTE_UPDATE_QUERY = 'NOTE_UPDATE_QUERY';
export const NOTE_UPDATE_SUCCESS = 'NOTE_UPDATE_SUCCESS';
export const NOTE_UPDATE_FAIL = 'NOTE_UPDATE_FAIL';
export const NOTE_UPDATE_RESET = 'NOTE_UPDATE_RESET';

export const NOTE_DELETE_QUERY = 'NOTE_DELETE_QUERY';
export const NOTE_DELETE_SUCCESS = 'NOTE_DELETE_SUCCESS';
export const NOTE_DELETE_FAIL = 'NOTE_DELETE_FAIL';
export const NOTE_DELETE_RESET = 'NOTE_DELETE_RESET';