export const TAG_LIST_QUERY = 'TAG_LIST_QUERY';
export const TAG_LIST_SUCCESS = 'TAG_LIST_SUCCESS';
export const TAG_LIST_FAIL = 'TAG_LIST_FAIL';

export const TAG_SELECT_QUERY = 'TAG_SELECT_QUERY';
export const TAG_SELECT_SUCCESS = 'TAG_SELECT_SUCCESS';
export const TAG_SELECT_FAIL = 'TAG_SELECT_FAIL';
export const TAG_SELECT_RESET = 'TAG_SELECT_RESET';

export const TAG_CREATE_QUERY = 'TAG_CREATE_QUERY';
export const TAG_CREATE_SUCCESS = 'TAG_CREATE_SUCCESS';
export const TAG_CREATE_FAIL = 'TAG_CREATE_FAIL';
export const TAG_CREATE_RESET = 'TAG_CREATE_RESET';

export const TAG_UPDATE_QUERY = 'TAG_UPDATE_QUERY';
export const TAG_UPDATE_SUCCESS = 'TAG_UPDATE_SUCCESS';
export const TAG_UPDATE_FAIL = 'TAG_UPDATE_FAIL';
export const TAG_UPDATE_RESET = 'TAG_UPDATE_RESET';

export const TAG_DELETE_QUERY = 'TAG_DELETE_QUERY';
export const TAG_DELETE_SUCCESS = 'TAG_DELETE_SUCCESS';
export const TAG_DELETE_FAIL = 'TAG_DELETE_FAIL';
export const TAG_DELETE_RESET = 'TAG_DELETE_RESET';